export const MODULE_SPECS = {
  standard: {
    maxCanvasWidth: 970,
    maxFileSizeBytes: 2 * 1024 * 1024,
    formats: ['image/jpeg', 'image/png'],
    colorSpace: 'sRGB',
    modules: [
      {
        id: 'header',
        name: 'Header Banner',
        description: 'Hero image at top of A+ page',
        width: 970,
        height: 600,
      },
      {
        id: 'banner',
        name: 'Section Banner',
        description: 'Full-width section separator',
        width: 970,
        height: 300,
      },
      {
        id: 'square_inset',
        name: 'Square Inset',
        description: 'Square feature callout',
        width: 300,
        height: 300,
      },
      {
        id: 'grid_large',
        name: 'Four-Image Grid (Large)',
        description: 'Grid item, standard size',
        width: 220,
        height: 220,
      },
      {
        id: 'grid_small',
        name: 'Four-Image Grid (Small)',
        description: 'Grid item, compact size',
        width: 135,
        height: 135,
      },
    ],
  },
  premium: {
    maxCanvasWidth: 1464,
    maxFileSizeBytes: 5 * 1024 * 1024,
    formats: ['image/jpeg', 'image/png'],
    colorSpace: 'sRGB',
    modules: [
      {
        id: 'hero',
        name: 'Hero Image',
        description: 'Large premium hero banner',
        width: 1464,
        height: 600,
      },
      {
        id: 'feature_large',
        name: 'Feature Image (Large)',
        description: 'Full-width feature with text overlay space',
        width: 1464,
        height: 900,
      },
      {
        id: 'carousel',
        name: 'Carousel Image',
        description: 'Image carousel slide',
        width: 1464,
        height: 600,
      },
      {
        id: 'hotspot',
        name: 'Hotspot Image',
        description: 'Static hotspot interactive image',
        width: 1464,
        height: 900,
      },
    ],
  },
  brand_story: {
    maxCanvasWidth: 970,
    maxFileSizeBytes: 2 * 1024 * 1024,
    formats: ['image/jpeg', 'image/png'],
    colorSpace: 'sRGB',
    modules: [
      {
        id: 'brand_hero',
        name: 'Brand Hero',
        description: 'Brand story hero banner',
        width: 970,
        height: 600,
      },
      {
        id: 'brand_logo',
        name: 'Brand Logo Card',
        description: 'Brand logo showcase',
        width: 300,
        height: 200,
      },
      {
        id: 'brand_card',
        name: 'Brand Story Card',
        description: 'Brand mission/values card',
        width: 220,
        height: 280,
      },
    ],
  },
}
